### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sinkthepink**

### CODE REVIEW

**Comment by monerica-project** [comment]
There's no apparent purpose to this.

**Comment by sinkthepink** [comment]
Not exactly sure if I understand. Mistake with index.html edit (not so familiar with github) or there is not a purpose with general anonymity advice, walking people through deGoogling phones, installing Linux OS on PCs and provisioning, configuring and maintaining LAMP cloud servers?

On Mon, 17 Jul 2023 12:17:55 -0700
monerica-project ***@***.***> wrote:

> There's no apparent purpose to this. 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/monerica-project/monerica/pull/83#issuecomment-1638730851
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
Q ***@***.***>

**Comment by sinkthepink** [comment]
Apologies. Not exactly a tech moron, but never used git and only really look around github sometimes at project code...

            <li>
                <a href="https://markqueen.com/">Mark Queen</a> - Confidential (digital) anonymity consulting, including strategic relocation,
                with secure hardware and cloud computing provisioning services. DeGoogled smartphones, Linux OS PCs, LAMP servers and more!
                Location: Worldwide. Processor: ONLY Coin Payments.  
            </li> 

On Mon, 17 Jul 2023 12:47:33 -0700
monerica-project ***@***.***> wrote:

> What exactly was the change you made? 
> 
> The entire file appeared edited and it was not possible to detect any difference.
> 
> Is there a link you're trying to add?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/monerica-project/monerica/pull/83#issuecomment-1638769232
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
Q ***@***.***>

**Comment by sinkthepink** [comment]
Apologies. Not exactly a tech moron, but never used git and only really look around github sometimes at project code...

'Technology' category

            <li>
                <a href="https://markqueen.com/">Mark Queen</a> - Confidential (digital) anonymity consulting, including strategic relocation,
                with secure hardware and cloud computing provisioning services. DeGoogled smartphones, Linux OS PCs, LAMP servers and more!
                Location: Worldwide. Processor: ONLY Coin Payments.  
            </li>

On Mon, 17 Jul 2023 12:47:33 -0700
monerica-project ***@***.***> wrote:

> What exactly was the change you made? 
> 
> The entire file appeared edited and it was not possible to detect any difference.
> 
> Is there a link you're trying to add?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/monerica-project/monerica/pull/83#issuecomment-1638769232
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
Q ***@***.***>

**Comment by sinkthepink** [comment]
Hello, Am I to assume business not approved for directory, or I need to figure out github system?

On Mon, 17 Jul 2023 12:47:33 -0700
monerica-project ***@***.***> wrote:

> What exactly was the change you made? 
> 
> The entire file appeared edited and it was not possible to detect any difference.
> 
> Is there a link you're trying to add?
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/monerica-project/monerica/pull/83#issuecomment-1638769232
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
Q ***@***.***>

**Comment by sinkthepink** [comment]
Cool! Sent some Monero...

On Tue, 18 Jul 2023 08:03:53 -0700
monerica-project ***@***.***> wrote:

> It's on the site now under It Services 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/monerica-project/monerica/pull/83#issuecomment-1640401403
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>


-- 
Q ***@***.***>

**Pull request closed without merging**
